export const aboutContent = {
  es: {
    eyebrow: '// sergio.monsalve · sobre mí',
    headline: ['Construyo software ', 'con datos', ', IA y un poco de hongos.'],
    roles: ['AI Software Engineer', 'Santa Elena, Antioquia 🇨🇴', '13 años en código · 7 en datos'],
    lede: 'Ingeniero de sistemas convertido en traductor entre datos y decisiones. Me gustan los problemas que se ven imposibles a primera vista, las cocinas con humo y los bosques de niebla. Trabajo mejor cuando hay un equipo pequeño, un objetivo claro y café cerca.',
    stackGroups: [
      { label: 'core · producción', chips: ['Python', 'FastAPI', 'Django', 'PostgreSQL', 'Dagster'] },
      { label: 'ai / llms', chips: ['LangChain', 'OpenAI', 'RAG', 'Embeddings', 'Vector DBs'] },
      { label: 'data · ml', chips: ['Pandas', 'Scikit-learn', 'ETL', 'Tableau', 'PowerBI'] },
      { label: 'cloud · infra', chips: ['AWS', 'GCP', 'Docker', 'Terraform'] },
    ],
    learning: { label: 'aprendiendo · 2026', chips: ['Rust', 'Eval / observabilidad LLM', 'Diseño de agentes'] },
    experienceLabel: '// experiencia',
    experienceTitle: 'Lo que he construido.',
    experienceDesc: 'Cuatro paradas que resumen el pivote de analista → ingeniero → IA. La línea es más limpia en retrospectiva que en el momento.',
    jobs: [
      {
        period: 'Nov 2022 → Abr 2025',
        current: true,
        role: 'Senior Python Developer',
        org: 'Globant · clientes enterprise (US/EU)',
        bullets: [
          'Diseñé un **pipeline RAG en LangChain + OpenAI** que redujo el tiempo de respuesta de soporte interno en ~60%.',
          'Migré orquestación batch a **Dagster**: 40+ assets versionados, observables y con backfills predecibles.',
          'APIs en **FastAPI** y servicios en **Go** para cargas con baja latencia.',
        ],
        chips: ['Python', 'LangChain', 'OpenAI', 'Dagster', 'FastAPI', 'Go'],
      },
      {
        period: 'Jun 2021 → May 2022',
        current: false,
        role: 'Co-founder & IT Lead',
        org: 'Human Living Data',
        bullets: [
          'Co-fundé una consultora de datos; armé el equipo técnico y el playbook de delivery desde cero.',
          'Construí **RPA + dashboards en Dash/Plotly** que automatizaron reportes operativos para 3 clientes.',
          'Aprendí, a las malas, que un buen contrato vale más que un buen modelo.',
        ],
        chips: ['Python', 'Scikit-learn', 'Dash/Plotly', 'RPA', 'AWS'],
      },
      {
        period: 'Mar 2020 → Jun 2021',
        current: false,
        role: 'IT Lead',
        org: 'Inmotion Group',
        bullets: [
          'Lideré el área técnica durante el primer año de pandemia; equipo de 4.',
          'Modelos de **geoanálisis (GIS) + ML** para optimizar rutas y zonas de servicio.',
        ],
        chips: ['Python', 'Pandas', 'Scikit-learn', 'AWS', 'GIS'],
      },
      {
        period: 'Nov 2018 → Mar 2020',
        current: false,
        role: 'Data Analyst',
        org: 'Leonisa',
        bullets: [
          'Mi primera vida con datos en serio: ETLs, modelos de demanda, dashboards para comercial.',
          'Pasé de "consultas SQL" a **pensar en arquitectura de datos**.',
        ],
        chips: ['Python', 'Tableau', 'PowerBI', 'ETL'],
      },
      {
        period: '2013 → 2018',
        current: false,
        role: 'Antes de los datos',
        org: 'Desarrollo backend, freelance, primeros proyectos',
        bullets: [
          'Backend en PHP/Python, integraciones con APIs, mucho aprender en producción.',
        ],
        chips: [],
        muted: true,
      },
    ],
    nowTitle: 'Ahora /now',
    nowItems: [
      { period: 'Mayo 2026', name: 'Tesis sobre evaluación de agentes LLM', where: '+ experimentos con orquestación local' },
      { period: 'en curso', name: 'Songosorhongo · cocina con hongos', where: 'probando recetas con cultivos propios' },
      { period: 'recurrente', name: 'Parapente en Antioquia', where: 'cuando el viento coopera' },
    ],
    beyondLabel: '// más allá del código',
    beyondTitle: ['Lo que ', 'no', ' dice el CV.'],
    beyondCards: [
      {
        glyph: '🍄  hongos',
        title: 'Songosorhongo',
        text: 'Un proyecto de cocina basada en hongos. Cultivo, fermento y cocino. La biología y el código se parecen más de lo que parece.',
        link: { href: 'https://songosorhongo.com', label: 'songosorhongo.com →' },
      },
      {
        glyph: '🪂  vuelo',
        title: 'Parapente',
        text: 'Volar sin motor obliga a leer el viento, la termal y el miedo. Mejor terapia que cualquier daily.',
        link: null,
      },
      {
        glyph: '📍  territorio',
        title: 'Santa Elena',
        text: 'Vivo en la montaña, a 30 minutos de Medellín. Trabajo remoto, niebla y silvestres. Es donde escribo mejor código.',
        link: null,
      },
    ],
    parapenteAlt: 'Parapente en las montañas de Antioquia',
    parapenteQuote: 'La mejor línea de código que he escrito la pensé en una termal a 2.800m.',
    parapenteQuoteEm: 'en una termal a 2.800m',
    parapenteSource: '— ensayo: más allá del código · 2026',
    parapenteLink: 'Leer ensayo completo →',
    ctaLabel: '// trabajemos',
    ctaTitle: ['¿Tienes un problema con datos, IA o ', 'backend con olor a producción', '? Hablemos.'],
    ctaWhatsApp: 'WhatsApp →',
    ctaGitHub: 'GitHub →',
  },
  en: {
    eyebrow: '// sergio.monsalve · about',
    headline: ['I build software ', 'with data', ', AI, and a bit of mushrooms.'],
    roles: ['AI Software Engineer', 'Santa Elena, Antioquia 🇨🇴', '13 years coding · 7 in data'],
    lede: 'Systems engineer turned translator between data and decisions. I like problems that look impossible at first glance, smoky kitchens, and foggy forests. I work best with a small team, a clear goal, and coffee nearby.',
    stackGroups: [
      { label: 'core · production', chips: ['Python', 'FastAPI', 'Django', 'PostgreSQL', 'Dagster'] },
      { label: 'ai / llms', chips: ['LangChain', 'OpenAI', 'RAG', 'Embeddings', 'Vector DBs'] },
      { label: 'data · ml', chips: ['Pandas', 'Scikit-learn', 'ETL', 'Tableau', 'PowerBI'] },
      { label: 'cloud · infra', chips: ['AWS', 'GCP', 'Docker', 'Terraform'] },
    ],
    learning: { label: 'learning · 2026', chips: ['Rust', 'LLM eval / observability', 'Agent design'] },
    experienceLabel: '// experience',
    experienceTitle: "What I've built.",
    experienceDesc: 'Four stops that trace the pivot from analyst → engineer → AI. The line looks cleaner in hindsight than it felt at the time.',
    jobs: [
      {
        period: 'Nov 2022 → Apr 2025',
        current: true,
        role: 'Senior Python Developer',
        org: 'Globant · enterprise clients (US/EU)',
        bullets: [
          'Designed a **RAG pipeline with LangChain + OpenAI** that cut internal support response time by ~60%.',
          'Migrated batch orchestration to **Dagster**: 40+ versioned, observable assets with predictable backfills.',
          '**FastAPI** APIs and **Go** services for low-latency workloads.',
        ],
        chips: ['Python', 'LangChain', 'OpenAI', 'Dagster', 'FastAPI', 'Go'],
      },
      {
        period: 'Jun 2021 → May 2022',
        current: false,
        role: 'Co-founder & IT Lead',
        org: 'Human Living Data',
        bullets: [
          'Co-founded a data consultancy; built the tech team and delivery playbook from scratch.',
          'Built **RPA + Dash/Plotly dashboards** that automated operational reports for 3 clients.',
          'Learned the hard way that a good contract beats a good model.',
        ],
        chips: ['Python', 'Scikit-learn', 'Dash/Plotly', 'RPA', 'AWS'],
      },
      {
        period: 'Mar 2020 → Jun 2021',
        current: false,
        role: 'IT Lead',
        org: 'Inmotion Group',
        bullets: [
          'Led the tech team through year one of the pandemic; team of 4.',
          '**GIS + ML** models to optimize routes and service zones.',
        ],
        chips: ['Python', 'Pandas', 'Scikit-learn', 'AWS', 'GIS'],
      },
      {
        period: 'Nov 2018 → Mar 2020',
        current: false,
        role: 'Data Analyst',
        org: 'Leonisa',
        bullets: [
          'My first serious life with data: ETLs, demand models, dashboards for commercial teams.',
          'Went from "SQL queries" to **thinking in data architecture**.',
        ],
        chips: ['Python', 'Tableau', 'PowerBI', 'ETL'],
      },
      {
        period: '2013 → 2018',
        current: false,
        role: 'Before data',
        org: 'Backend dev, freelance, early projects',
        bullets: ['PHP/Python backend, API integrations, lots of learning in production.'],
        chips: [],
        muted: true,
      },
    ],
    nowTitle: 'Now /now',
    nowItems: [
      { period: 'May 2026', name: 'Thesis on LLM agent evaluation', where: '+ local orchestration experiments' },
      { period: 'ongoing', name: 'Songosorhongo · mushroom cooking', where: 'testing recipes with home-grown fungi' },
      { period: 'recurring', name: 'Paragliding in Antioquia', where: 'when the wind cooperates' },
    ],
    beyondLabel: '// beyond the code',
    beyondTitle: ['What the CV ', "doesn't", ' say.'],
    beyondCards: [
      {
        glyph: '🍄  mushrooms',
        title: 'Songosorhongo',
        text: "A mushroom-based cooking project. I grow, ferment, and cook. Biology and code are more alike than they look.",
        link: { href: 'https://songosorhongo.com', label: 'songosorhongo.com →' },
      },
      {
        glyph: '🪂  flying',
        title: 'Paragliding',
        text: 'Flying without an engine means reading the wind, the thermal, and the fear. Better therapy than any daily standup.',
        link: null,
      },
      {
        glyph: '📍  territory',
        title: 'Santa Elena',
        text: "I live in the mountains, 30 minutes from Medellín. Remote work, fog, and wild mushrooms. It's where I write my best code.",
        link: null,
      },
    ],
    parapenteAlt: 'Paragliding over the mountains of Antioquia',
    parapenteQuote: 'The best line of code I ever wrote came to me on a thermal at 2,800m.',
    parapenteQuoteEm: 'on a thermal at 2,800m',
    parapenteSource: '— essay: beyond the code · 2026',
    parapenteLink: 'Read full essay →',
    ctaLabel: '// let\'s work',
    ctaTitle: ['Got a problem with data, AI, or ', 'backend that smells like production', '? Let\'s talk.'],
    ctaWhatsApp: 'WhatsApp →',
    ctaGitHub: 'GitHub →',
  },
}

export type AboutLocale = keyof typeof aboutContent
