import { describe, it, expect } from 'vitest'
import { isUuid } from '../unified-library'

describe('isUuid', () => {
  it('returns true for a valid UUID v4', () => {
    expect(isUuid('550e8400-e29b-41d4-a716-446655440000')).toBe(true)
  })

  it('returns true for a UUID generated by Supabase gen_random_uuid()', () => {
    expect(isUuid('a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d')).toBe(true)
  })

  it('returns false for an Audible ASIN', () => {
    expect(isUuid('B001TEST00')).toBe(false)
  })

  it('returns false for a standard 10-char ASIN', () => {
    expect(isUuid('0062945149')).toBe(false)
  })

  it('returns false for an empty string', () => {
    expect(isUuid('')).toBe(false)
  })
})
